[package]
cairo-version = "2.0.1"
name = "stark_lander"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
# Locking to latest commit (so future builds work even with incompatible changes in cubit)
cubit = { git = "https://github.com/influenceth/cubit", rev = "f888156" }
dojo = { git = "https://github.com/dojoengine/dojo" }
lander_math = { path = "./lander" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
account_address = "0x03ee9e18edc71a6df30ac3aca2e0b02a198fbce19b7480a63a0d71cbd76652e0"
private_key = "0x0300001800000000300000180000000000030000000000003006001800006600"
rpc_url = "http://localhost:5050/"
# world_address = "0x37789dc51b4d31948b9994f92fdfd72c800002e1823d96e3d77df437659d08f"

# keystore_path = "../keystore.json"
# keystore_password = "password"
